name: CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: install pytest 
        run: |
          pip install bandit
      - name: security
        run: bandit -r .
      - name: github file
        uses: actions/upload-artifact@v4
        with:
            name: coverage-report
            path: coverage.xml
